[BIO-6387-6392] added darwin core and embargo field
dbca-wa/ckanext-dbca pull request #9
Opened 2023-12-14 02:23 UTC by awset

https://dev.azure.com/BIO-WA/CKAN%20Mod/_workitems/edit/6387/
https://dev.azure.com/BIO-WA/CKAN%20Mod/_workitems/edit/6392/

changes
- added darwin core format, OOTB ckan need to have 1 resource with this format to be created before it shows up in the dropdown, 
- darwin core also visible on the search facet.
- added embargo field and its validator
- added command to auto publish when the embargo data is equal or less than today
- added email notification for dataset will be auto published in the next 7 days.

![image](https://github.com/dbca-wa/ckanext-dbca/assets/1538818/50100849-41e0-459f-a280-22630eb0efac)
![image](https://github.com/dbca-wa/ckanext-dbca/assets/1538818/531577d1-647f-485d-ae4e-578fdd6c070a)
![image](https://github.com/dbca-wa/ckanext-dbca/assets/1538818/727bc3c1-6713-4da9-8224-fefd81e73aa8)
![image](https://github.com/dbca-wa/ckanext-dbca/assets/1538818/efd6b40a-023e-4400-a365-4eb8801b1b23)

2023-12-19 03:49 UTC, MarkCalvert commented on ckanext/dbca/cli.py
> +                tk.abort(
Please remove.
Use tk.error_shout(error_msg)

2023-12-19 03:50 UTC, MarkCalvert commented on ckanext/dbca/dbca_dataset.yaml
> +  preset: dbca_embargo_date
Remove preset

2023-12-19 03:54 UTC, MarkCalvert requested changes

2023-12-19 03:54 UTC, MarkCalvert commented on ckanext/dbca/dbca_presets.json
> +{
Remove preset

2023-12-19 03:54 UTC, MarkCalvert commented on ckanext/dbca/logic/action.py
> +    utc_now = datetime.datetime.utcnow().date()
Convert to Perth timezone for compares

2023-12-20 02:33 UTC, awset commented on ckanext/dbca/cli.py
> +                tk.abort(
abort removed, added error_shout

2023-12-20 02:33 UTC, awset commented on ckanext/dbca/dbca_dataset.yaml
> +  preset: dbca_embargo_date
preset removed

2023-12-20 02:33 UTC, awset commented on ckanext/dbca/dbca_presets.json
> +{
file removed

2023-12-20 03:19 UTC, awset commented on ckanext/dbca/logic/action.py
> +    utc_now = datetime.datetime.utcnow().date()
converted

2023-12-20 04:02 UTC, MarkCalvert approved these changes

2023-12-20 04:02 UTC, merged